### ISSUE TITLE
This is a new issue

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/testapp#1]
@kyukyung this is how it works here

**Comment by gnuwilliam** [comment]
Hélio!

**Comment by ellisonleao** [comment]
This is a reply from GMAIL client

2015-12-02 14:58 GMT-02:00 William Oliveira notifications@github.com:

> Hélio!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ellisonleao/testapp/issues/1#issuecomment-161363891.

## 

Ellison Leão
about.me/ellison
[image: Ellison Leão on about.me]
  http://about.me/ellison

**Comment by ellisonleao** [comment]
A reply with an Image

2015-12-02 14:58 GMT-02:00 William Oliveira notifications@github.com:

> Hélio!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ellisonleao/testapp/issues/1#issuecomment-161363891.

## 

Ellison Leão
about.me/ellison
[image: Ellison Leão on about.me]
  http://about.me/ellison

**Comment by gnuwilliam** [comment]
![Test](https://blog.optimizely.com/wp-content/uploads/2013/06/Screen-Shot-2013-06-11-at-6.27.42-PM.png)

**Comment by ellisonleao** [comment]
This is a reply with a attachment image

2015-12-02 14:58 GMT-02:00 William Oliveira notifications@github.com:

> Hélio!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ellisonleao/testapp/issues/1#issuecomment-161363891.

## 

Ellison Leão
about.me/ellison
[image: Ellison Leão on about.me]
  http://about.me/ellison

**Comment by ellisonleao** [comment]
Reply directly from github with an uploaded image

![thumbs](https://cloud.githubusercontent.com/assets/178641/11538075/534f549a-9907-11e5-949d-6c4246770bc2.png)
